sudo: false

language: node_js

node_js:
  - 4
  - 5

services:
  - mongodb
  - redis

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

install: make

script: make test

after_success: make coveralls
