sudo: false

language: node_js

node_js:
  - 4
  - 5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - mongodb

install: make

script: make test

after_success: make coveralls
